//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EskholFitness.BLTests.Controller {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesEN() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EskholFitness.BLTests.Controller.MessagesEN", typeof(MessagesEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что Вы хотите сделать?\ne - ввести новый прием пищи..
        /// </summary>
        internal static string ActionChoice_msg {
            get {
                return ResourceManager.GetString("ActionChoice_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введитe свою дату рождения: (dd/mm/yyyy).
        /// </summary>
        internal static string EnterBirthDate_msg {
            get {
                return ResourceManager.GetString("EnterBirthDate_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели пльзователя с такими данными:.
        /// </summary>
        internal static string EnterdUser_msg {
            get {
                return ResourceManager.GetString("EnterdUser_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введитe свой пол:.
        /// </summary>
        internal static string EnterGender_msg {
            get {
                return ResourceManager.GetString("EnterGender_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введитe свой рост:.
        /// </summary>
        internal static string EnterHeight_msg {
            get {
                return ResourceManager.GetString("EnterHeight_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введитe свое имя:.
        /// </summary>
        internal static string EnterName_msg {
            get {
                return ResourceManager.GetString("EnterName_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите наименование продукта:.
        /// </summary>
        internal static string EnterProductName_msg {
            get {
                return ResourceManager.GetString("EnterProductName_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите массупорции:.
        /// </summary>
        internal static string EnterProductWeight_msg {
            get {
                return ResourceManager.GetString("EnterProductWeight_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введитe свой вес:.
        /// </summary>
        internal static string EnterWeight_msg {
            get {
                return ResourceManager.GetString("EnterWeight_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод пола. Наименование пола не моежт быть пустым..
        /// </summary>
        internal static string ReapeatGengerEntering_msg {
            get {
                return ResourceManager.GetString("ReapeatGengerEntering_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод имени. Имя не может быть пусто..
        /// </summary>
        internal static string ReapeatNameEntering_msg {
            get {
                return ResourceManager.GetString("ReapeatNameEntering_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод даты рождения. Пользователь не моежт быть старше 120 лет или еще не родиться..
        /// </summary>
        internal static string RepeatBirthDateEntering_msg {
            get {
                return ResourceManager.GetString("RepeatBirthDateEntering_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод роста:.
        /// </summary>
        internal static string RepeatHeightEntering_msg {
            get {
                return ResourceManager.GetString("RepeatHeightEntering_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод наименования продукта. Наименование продукта не моежт быть пустым..
        /// </summary>
        internal static string RepeatProductNameEntering_msg {
            get {
                return ResourceManager.GetString("RepeatProductNameEntering_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод. Не получилось преобразовать в дробное число..
        /// </summary>
        internal static string RepeatProductWeight_msg {
            get {
                return ResourceManager.GetString("RepeatProductWeight_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод веса. Вес не может быть меньше либо равным нулю:.
        /// </summary>
        internal static string RepeatWeightEntering_msg {
            get {
                return ResourceManager.GetString("RepeatWeightEntering_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранено.
        /// </summary>
        internal static string Saved_msg {
            get {
                return ResourceManager.GetString("Saved_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вас приветствует программа EskholFitness!.
        /// </summary>
        internal static string Welcoming_msg {
            get {
                return ResourceManager.GetString("Welcoming_msg", resourceCulture);
            }
        }
    }
}
